
mAP:
  #--------------------------------------------------------------------------------------#
  #   此处的classes_path用于指定需要测量VOC_map的类别
  #   一般情况下与训练和预测所用的classes_path一致即可
  #--------------------------------------------------------------------------------------#
  classes_path: 'configs/data/voc_classes.txt'

  #--------------------------------------------------------------------------------------#
  #   MINOVERLAP用于指定想要获得的mAP0.x，mAP0.x的意义是什么请同学们百度一下。
  #   比如计算mAP0.75，可以设定MINOVERLAP = 0.75。
  #
  #   当某一预测框与真实框重合度大于MINOVERLAP时，该预测框被认为是正样本，否则为负样本。
  #   因此MINOVERLAP的值越大，预测框要预测的越准确才能被认为是正样本，此时算出来的mAP值越低，
  #--------------------------------------------------------------------------------------#
  MINOVERLAP: 0.5
  #--------------------------------------------------------------------------------------#
  #   受到mAP计算原理的限制，网络在计算mAP时需要获得近乎所有的预测框，这样才可以计算mAP
  #   因此，confidence的值应当设置的尽量小进而获得全部可能的预测框。
  #   
  #   该值一般不调整。因为计算mAP需要获得近乎所有的预测框，此处的confidence不能随便更改。
  #   想要获得不同门限值下的Recall和Precision值，请修改下方的score_threhold。
  #--------------------------------------------------------------------------------------#
  confidence: 0.001
  #--------------------------------------------------------------------------------------#
  #   预测时使用到的非极大抑制值的大小，越大表示非极大抑制越不严格。
  #   
  #   该值一般不调整。
  #--------------------------------------------------------------------------------------#
  nms_iou: 0.5
  #---------------------------------------------------------------------------------------------------------------#
  #   Recall和Precision不像AP是一个面积的概念，因此在门限值不同时，网络的Recall和Precision值是不同的。
  #   
  #   默认情况下，本代码计算的Recall和Precision代表的是当门限值为0.5（此处定义为score_threhold）时所对应的Recall和Precision值。
  #   因为计算mAP需要获得近乎所有的预测框，上面定义的confidence不能随便更改。
  #   这里专门定义一个score_threhold用于代表门限值，进而在计算mAP时找到门限值对应的Recall和Precision值。
  #---------------------------------------------------------------------------------------------------------------#
  score_threhold: 0.5
  #-------------------------------------------------------#
  #   map_vis用于指定是否开启VOC_map计算的可视化
  #-------------------------------------------------------#
  map_vis: True
  #-------------------------------------------------------#
  #   指向VOC数据集所在的文件夹
  #   默认指向根目录下的VOC数据集
  #-------------------------------------------------------#
  VOCdevkit_path: 'datasets/VOCdevkit'
  #-------------------------------------------------------#
  #   结果输出的文件夹，默认为map_out
  #-------------------------------------------------------#
  map_out_path: 'map_out'


defaults:
  - enhancer: basic
  - detector: yolov8
  # 让Hydra不切换工作目录
  - hydra: hydra